export const mockWorkers = [
    {
        id: "w1",
        name: "Muhammad Ali",
        email: "ali@example.com",
        phone: "+92 300 1234567",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-01-15",
        category: "electrician",
        bio: "15 years experience in residential and commercial electrical work. Specialized in wiring, installations, and troubleshooting.",
        experience: 15,
        rating: 4.9,
        reviewCount: 127,
        jobsCompleted: 342,
        priceRange: { min: 800, max: 2500 },
        specialties: ["Wiring", "Installation", "Troubleshooting", "Solar Panels"],
        availableToday: true,
        verified: { cnic: true, police: true, skill: true, backgroundCheck: true },
        portfolio: [
            "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
        ],
        services: [
            { id: "s1", name: "Wiring Repair", priceMin: 800, priceMax: 1500, duration: "1-2 hours" },
            { id: "s2", name: "New Installation", priceMin: 1500, priceMax: 2500, duration: "2-4 hours" },
            { id: "s3", name: "Circuit Breaker Repair", priceMin: 1000, priceMax: 2000, duration: "1-2 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "09:00", endTime: "18:00" },
            tuesday: { available: true, startTime: "09:00", endTime: "18:00" },
            wednesday: { available: true, startTime: "09:00", endTime: "18:00" },
            thursday: { available: true, startTime: "09:00", endTime: "18:00" },
            friday: { available: true, startTime: "09:00", endTime: "17:00" },
            saturday: { available: true, startTime: "10:00", endTime: "16:00" },
            sunday: { available: false },
            emergencyAvailable: true,
        },
        location: "DHA Phase 5, Karachi",
        memberSince: "January 2024",
    },
    {
        id: "w2",
        name: "Ahmed Khan",
        email: "ahmed@example.com",
        phone: "+92 300 2345678",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-02-20",
        category: "plumber",
        bio: "Expert plumber with 10 years experience. Specialized in pipe repairs, bathroom fittings, and water heater installations.",
        experience: 10,
        rating: 4.8,
        reviewCount: 89,
        jobsCompleted: 215,
        priceRange: { min: 600, max: 2000 },
        specialties: ["Pipe Repair", "Bathroom Fittings", "Water Heater", "Drainage"],
        availableToday: true,
        verified: { cnic: true, police: true, skill: true, backgroundCheck: true },
        portfolio: [
            "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400",
        ],
        services: [
            { id: "s4", name: "Pipe Repair", priceMin: 600, priceMax: 1200, duration: "1-2 hours" },
            { id: "s5", name: "Tap Installation", priceMin: 500, priceMax: 800, duration: "30 min - 1 hour" },
            { id: "s6", name: "Drainage Cleaning", priceMin: 800, priceMax: 1500, duration: "1-2 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "08:00", endTime: "19:00" },
            tuesday: { available: true, startTime: "08:00", endTime: "19:00" },
            wednesday: { available: true, startTime: "08:00", endTime: "19:00" },
            thursday: { available: true, startTime: "08:00", endTime: "19:00" },
            friday: { available: true, startTime: "08:00", endTime: "17:00" },
            saturday: { available: true, startTime: "09:00", endTime: "15:00" },
            sunday: { available: false },
            emergencyAvailable: true,
        },
        location: "Gulshan-e-Iqbal, Karachi",
        memberSince: "February 2024",
    },
    {
        id: "w3",
        name: "Hassan Raza",
        email: "hassan@example.com",
        phone: "+92 300 3456789",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-01-10",
        category: "ac-mechanic",
        bio: "Certified AC technician with 8 years experience. Expert in split AC, window AC, and inverter AC systems.",
        experience: 8,
        rating: 4.7,
        reviewCount: 156,
        jobsCompleted: 423,
        priceRange: { min: 1500, max: 5000 },
        specialties: ["Split AC", "Window AC", "Inverter AC", "Gas Refill", "Installation"],
        availableToday: false,
        verified: { cnic: true, police: true, skill: true, backgroundCheck: true },
        portfolio: [
            "https://images.unsplash.com/photo-1631545806609-6578b32a2e4b?w=400",
        ],
        services: [
            { id: "s7", name: "AC Gas Refill", priceMin: 2500, priceMax: 3500, duration: "1-2 hours" },
            { id: "s8", name: "AC Deep Cleaning", priceMin: 1500, priceMax: 2500, duration: "1 hour" },
            { id: "s9", name: "AC Installation", priceMin: 3500, priceMax: 5000, duration: "2-3 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "09:00", endTime: "18:00" },
            tuesday: { available: true, startTime: "09:00", endTime: "18:00" },
            wednesday: { available: true, startTime: "09:00", endTime: "18:00" },
            thursday: { available: true, startTime: "09:00", endTime: "18:00" },
            friday: { available: true, startTime: "09:00", endTime: "17:00" },
            saturday: { available: false },
            sunday: { available: false },
            emergencyAvailable: false,
        },
        location: "Clifton, Karachi",
        memberSince: "January 2024",
    },
    {
        id: "w4",
        name: "Imran Sheikh",
        email: "imran@example.com",
        phone: "+92 300 4567890",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-03-05",
        category: "carpenter",
        bio: "Master carpenter with 20 years of experience. Specialized in custom furniture, kitchen cabinets, and woodwork.",
        experience: 20,
        rating: 4.9,
        reviewCount: 203,
        jobsCompleted: 567,
        priceRange: { min: 2000, max: 15000 },
        specialties: ["Custom Furniture", "Kitchen Cabinets", "Door Installation", "Wood Repair"],
        availableToday: true,
        verified: { cnic: true, police: true, skill: true, backgroundCheck: true },
        portfolio: [
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
            "https://images.unsplash.com/photo-1616464916356-3a777b2b60b1?w=400",
        ],
        services: [
            { id: "s10", name: "Furniture Repair", priceMin: 2000, priceMax: 5000, duration: "2-4 hours" },
            { id: "s11", name: "Cabinet Installation", priceMin: 5000, priceMax: 15000, duration: "1-2 days" },
            { id: "s12", name: "Door Fitting", priceMin: 2500, priceMax: 4000, duration: "2-3 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "08:00", endTime: "17:00" },
            tuesday: { available: true, startTime: "08:00", endTime: "17:00" },
            wednesday: { available: true, startTime: "08:00", endTime: "17:00" },
            thursday: { available: true, startTime: "08:00", endTime: "17:00" },
            friday: { available: true, startTime: "08:00", endTime: "16:00" },
            saturday: { available: true, startTime: "09:00", endTime: "14:00" },
            sunday: { available: false },
            emergencyAvailable: false,
        },
        location: "PECHS, Karachi",
        memberSince: "March 2024",
    },
    {
        id: "w5",
        name: "Farhan Malik",
        email: "farhan@example.com",
        phone: "+92 300 5678901",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-02-15",
        category: "painter",
        bio: "Professional painter with 12 years experience. Expert in interior and exterior painting, wall textures, and waterproofing.",
        experience: 12,
        rating: 4.6,
        reviewCount: 78,
        jobsCompleted: 189,
        priceRange: { min: 1500, max: 8000 },
        specialties: ["Interior Painting", "Exterior Painting", "Wall Textures", "Waterproofing"],
        availableToday: true,
        verified: { cnic: true, police: true, skill: true, backgroundCheck: false },
        portfolio: [
            "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400",
        ],
        services: [
            { id: "s13", name: "Room Painting", priceMin: 3000, priceMax: 6000, duration: "1 day" },
            { id: "s14", name: "Wall Texture", priceMin: 2000, priceMax: 4000, duration: "4-6 hours" },
            { id: "s15", name: "Waterproofing", priceMin: 1500, priceMax: 8000, duration: "1-2 days" },
        ],
        availability: {
            monday: { available: true, startTime: "07:00", endTime: "18:00" },
            tuesday: { available: true, startTime: "07:00", endTime: "18:00" },
            wednesday: { available: true, startTime: "07:00", endTime: "18:00" },
            thursday: { available: true, startTime: "07:00", endTime: "18:00" },
            friday: { available: true, startTime: "07:00", endTime: "17:00" },
            saturday: { available: true, startTime: "08:00", endTime: "16:00" },
            sunday: { available: false },
            emergencyAvailable: false,
        },
        location: "North Nazimabad, Karachi",
        memberSince: "February 2024",
    },
    {
        id: "w6",
        name: "Bilal Ahmed",
        email: "bilal@example.com",
        phone: "+92 300 6789012",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-01-25",
        category: "electrician",
        bio: "Skilled electrician specializing in industrial and commercial electrical systems. 7 years of experience.",
        experience: 7,
        rating: 4.5,
        reviewCount: 64,
        jobsCompleted: 156,
        priceRange: { min: 700, max: 2000 },
        specialties: ["Industrial Wiring", "Commercial Systems", "UPS Installation", "Generator Setup"],
        availableToday: true,
        verified: { cnic: true, police: true, skill: true, backgroundCheck: true },
        portfolio: [],
        services: [
            { id: "s16", name: "Electrical Inspection", priceMin: 700, priceMax: 1200, duration: "1-2 hours" },
            { id: "s17", name: "UPS Installation", priceMin: 1500, priceMax: 2000, duration: "2-3 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "09:00", endTime: "19:00" },
            tuesday: { available: true, startTime: "09:00", endTime: "19:00" },
            wednesday: { available: true, startTime: "09:00", endTime: "19:00" },
            thursday: { available: true, startTime: "09:00", endTime: "19:00" },
            friday: { available: true, startTime: "09:00", endTime: "18:00" },
            saturday: { available: true, startTime: "10:00", endTime: "16:00" },
            sunday: { available: false },
            emergencyAvailable: true,
        },
        location: "Saddar, Karachi",
        memberSince: "January 2024",
    },
    {
        id: "w7",
        name: "Usman Tariq",
        email: "usman@example.com",
        phone: "+92 300 7890123",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-03-10",
        category: "plumber",
        bio: "Plumbing expert with focus on modern bathroom installations and smart water systems.",
        experience: 6,
        rating: 4.4,
        reviewCount: 42,
        jobsCompleted: 98,
        priceRange: { min: 500, max: 1800 },
        specialties: ["Modern Bathrooms", "Water Tanks", "Smart Systems", "Leakage Repair"],
        availableToday: false,
        verified: { cnic: true, police: true, skill: false, backgroundCheck: true },
        portfolio: [],
        services: [
            { id: "s18", name: "Leakage Repair", priceMin: 500, priceMax: 1000, duration: "1-2 hours" },
            { id: "s19", name: "Tank Installation", priceMin: 1200, priceMax: 1800, duration: "2-4 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "10:00", endTime: "18:00" },
            tuesday: { available: true, startTime: "10:00", endTime: "18:00" },
            wednesday: { available: false },
            thursday: { available: true, startTime: "10:00", endTime: "18:00" },
            friday: { available: true, startTime: "10:00", endTime: "17:00" },
            saturday: { available: true, startTime: "11:00", endTime: "15:00" },
            sunday: { available: false },
            emergencyAvailable: false,
        },
        location: "Korangi, Karachi",
        memberSince: "March 2024",
    },
    {
        id: "w8",
        name: "Kamran Shah",
        email: "kamran@example.com",
        phone: "+92 300 8901234",
        role: "worker",
        avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=200&h=200&fit=crop&crop=face",
        createdAt: "2024-02-28",
        category: "ac-mechanic",
        bio: "Specialized in inverter AC technology and central air conditioning systems. 5 years experience.",
        experience: 5,
        rating: 4.3,
        reviewCount: 35,
        jobsCompleted: 87,
        priceRange: { min: 1200, max: 4500 },
        specialties: ["Inverter AC", "Central AC", "Ducted Systems", "Maintenance"],
        availableToday: true,
        verified: { cnic: true, police: false, skill: true, backgroundCheck: false },
        portfolio: [],
        services: [
            { id: "s20", name: "AC Maintenance", priceMin: 1200, priceMax: 2000, duration: "1-2 hours" },
            { id: "s21", name: "Central AC Service", priceMin: 3000, priceMax: 4500, duration: "3-4 hours" },
        ],
        availability: {
            monday: { available: true, startTime: "08:00", endTime: "17:00" },
            tuesday: { available: true, startTime: "08:00", endTime: "17:00" },
            wednesday: { available: true, startTime: "08:00", endTime: "17:00" },
            thursday: { available: true, startTime: "08:00", endTime: "17:00" },
            friday: { available: true, startTime: "08:00", endTime: "16:00" },
            saturday: { available: false },
            sunday: { available: false },
            emergencyAvailable: true,
        },
        location: "Malir, Karachi",
        memberSince: "February 2024",
    },
];

export const mockBookings = [
    {
        id: "b1",
        customerId: "c1",
        workerId: "w1",
        worker: {
            name: "Muhammad Ali",
            photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
            category: "electrician",
            phone: "+92 300 1234567",
        },
        customer: {
            name: "Asad Hussain",
            phone: "+92 321 1234567",
            email: "asad@example.com",
        },
        service: "Wiring Repair",
        serviceDescription: "Need to fix faulty wiring in the bedroom",
        date: "2026-01-28",
        timeSlot: "10:00 AM - 12:00 PM",
        address: "House 45, Street 12, DHA Phase 6, Karachi",
        status: "confirmed",
        estimatedPrice: { min: 800, max: 1500 },
        platformFee: 200,
        createdAt: "2026-01-25T10:30:00Z",
        timeline: [
            { event: "Booking created", timestamp: "2026-01-25T10:30:00Z" },
            { event: "Confirmed by worker", timestamp: "2026-01-25T11:15:00Z" },
        ],
    },
    {
        id: "b2",
        customerId: "c1",
        workerId: "w3",
        worker: {
            name: "Hassan Raza",
            photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
            category: "ac-mechanic",
            phone: "+92 300 3456789",
        },
        customer: {
            name: "Asad Hussain",
            phone: "+92 321 1234567",
            email: "asad@example.com",
        },
        service: "AC Gas Refill",
        serviceDescription: "AC not cooling properly, needs gas refill",
        date: "2026-01-20",
        timeSlot: "2:00 PM - 4:00 PM",
        address: "House 45, Street 12, DHA Phase 6, Karachi",
        status: "completed",
        estimatedPrice: { min: 2500, max: 3500 },
        finalPrice: 3000,
        platformFee: 300,
        paymentMethod: "cash",
        paymentStatus: "paid",
        rating: 5,
        review: "Excellent service! Very professional and completed the work on time.",
        createdAt: "2026-01-18T09:00:00Z",
        timeline: [
            { event: "Booking created", timestamp: "2026-01-18T09:00:00Z" },
            { event: "Confirmed by worker", timestamp: "2026-01-18T09:30:00Z" },
            { event: "Worker arrived", timestamp: "2026-01-20T14:00:00Z" },
            { event: "Work started", timestamp: "2026-01-20T14:15:00Z" },
            { event: "Work completed", timestamp: "2026-01-20T15:30:00Z" },
        ],
    },
    {
        id: "b3",
        customerId: "c1",
        workerId: "w4",
        worker: {
            name: "Imran Sheikh",
            photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
            category: "carpenter",
            phone: "+92 300 4567890",
        },
        customer: {
            name: "Asad Hussain",
            phone: "+92 321 1234567",
            email: "asad@example.com",
        },
        service: "Furniture Repair",
        date: "2026-01-30",
        timeSlot: "9:00 AM - 11:00 AM",
        address: "House 45, Street 12, DHA Phase 6, Karachi",
        status: "pending",
        estimatedPrice: { min: 2000, max: 5000 },
        platformFee: 300,
        createdAt: "2026-01-25T14:00:00Z",
        timeline: [
            { event: "Booking created", timestamp: "2026-01-25T14:00:00Z" },
        ],
    },
];

export const mockReviews = [
    {
        id: "r1",
        workerId: "w1",
        customerId: "c1",
        customerName: "Asad H.",
        bookingId: "b1",
        service: "Wiring Repair",
        rating: 5,
        text: "Muhammad Ali did an excellent job fixing the electrical issues in my home. Very professional and punctual.",
        createdAt: "2026-01-15T12:00:00Z",
    },
    {
        id: "r2",
        workerId: "w1",
        customerId: "c2",
        customerName: "Fatima K.",
        bookingId: "b4",
        service: "New Installation",
        rating: 5,
        text: "Great work on the new electrical installation. Would highly recommend!",
        createdAt: "2026-01-10T15:30:00Z",
    },
    {
        id: "r3",
        workerId: "w1",
        customerId: "c3",
        customerName: "Omar S.",
        bookingId: "b5",
        service: "Circuit Breaker Repair",
        rating: 4,
        text: "Good service, arrived on time and fixed the issue quickly.",
        createdAt: "2026-01-05T10:00:00Z",
    },
];

export const getCategoryCount = (category) => {
    return mockWorkers.filter((w) => w.category === category).length;
};

export const platformStats = {
    happyCustomers: 500,
    verifiedWorkers: 150,
    avgRating: 4.8,
    jobsCompleted: 10000,
};
